baseURL = "https://anderson-pids.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Anderson Pids"
title = "Blog do Anderson Pids"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "Copyright © [Vitae](https://github.com/dataCobra/hugo-vitae) theme. All rights reserved."

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-186928098-1"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["anderson","pids","computer","blog"]

	# Add meta description in head part
	description = "O blog de experiências de computação, algoritmos, tecnologia e otras cositas más"

	# Add pagetitle to homepage <title> tag
	pagetitle = "Coisas interessantes de computação"

	# Add a subtitle to your website
	subtitle = "Blog de experiências de computação e outras bizarrices"

	# Activate to show authors on pages if available
	# listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/img/vitae.jpg"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
    mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = true

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
shortname = "andersonpids" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url  = "https://github.com/anderson-pids/"

[[params.social]]
name = "Linkedin"
icon = "fab fa-linkedin"
url  = "https://www.linkedin.com/in/andersonpimentel/"

# [[params.social]]
# name = "Email"
# icon = "fas fa-envelope"
# cmd = "mailto:apds.anderson@gmail.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url  = "/index.xml"
