version: '3.7'

services:
  blog:
    image: 'klakegg/hugo:0.83.1-alpine'
    container_name: blog
    networks:
      - development
    ports:
      - '1313:1313'
    volumes:
      - ".:/src"
    command: server -D  

networks:
  development:
    name: apids_network
    driver: bridge