services:
  blog:
    image: ghcr.io/gohugoio/hugo:v0.167.0
    container_name: blog
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "1313:1313"
    volumes:
      - ".:/project"
    command: server --bind 0.0.0.0 --buildDrafts --baseURL http://localhost:1313/ --appendPort=false
